import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'henrik' at '5/14/15 6:42 PM' with Gradle 2.4
 *
 * @author henrik, @date 5/14/15 6:42 PM
 */
public class NnblMainApplicationTest {
    @Test public void testSomeLibraryMethod() {
        NnblMainApplication classUnderTest = new NnblMainApplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
